### ISSUE TITLE
Support Preview flag in ContentByContentTypeQuery

### ISSUE THREAD

**Issue by jdpnielsen** [nikcio/Nikcio.UHeadless#229]
### Feature summary

Ideally, all 'basic queries' should support preview mode - this would make it much easier to build applications with preview support.

**Comment by nikcio** [comment]
Hi @jdpnielsen 

The reason `ContentByContentTypeQuery` doesn't support preview is because the underlying method that is called in Umbraco doesn't take a parameter of preview. So we would either need to have a new method added to Umbraco in order to support this or fetch the content data in some other way.

The underlying call is to `IPublishedCache.GetByContentType(IPublishedContentType contentType);`. See `src\Nikcio.UHeadless.Content\Queries\ContentByContentTypeQuery.cs`

**Comment by jdpnielsen** [comment]
@nikcio That makes sense.

I just took a look at the underlying code for GetByContentType: https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Core/PublishedCache/PublishedCacheBase.cs#L91-L98 (hope this is the correct one anyway)

```cs
    public virtual IEnumerable<IPublishedContent> GetByContentType(IPublishedContentType contentType) =>

        // this is probably not super-efficient, but works
        // some cache implementation may want to override it, though
        GetAtRoot()
            .SelectMany(x => x.DescendantsOrSelf(_variationContextAccessor!))
            .Where(x => x.ContentType.Id == contentType.Id);
```

It seems the GetAtRoot() function take a preview parameter. Do you think it would make sense to implement a variant of this with preview support in this repo?

**Comment by nikcio** [comment]
@jdpnielsen I never knew the implementation of `GetByContentType` was so simple 😆 

But yeah we can totally replace `GetByContentType` with this and pass a preview parameter.
But it would be a breaking change because we will need to inject the variation context accessor to the query and add the preview parameter. But I'm already working on v5 so it can be included in that 😄 

Do you want to take a swing at opening a PR for it?

**Comment by nikcio** [comment]
This will be included in version 5
