### ISSUE TITLE
How to authorize data access with OAUTH or JWT?

### ISSUE THREAD

**Issue by biapar** [nikcio/Nikcio.UHeadless#83]
How to authorize data access with OAUTH or JWT?

**Comment by nikcio** [comment]
Hi @biapar,

This is pretty simple. The package supports all authorization options that Asp Net Core comes with out of the box. This works by setting up the authentication and authorization for your solution as you would normally and creating custom Query models.

An example can be seen in the test project here: https://github.com/nikcio/Nikcio.UHeadless/blob/v3/contrib/test/v10/Models/CustomContentQuery.cs

## Step-by-step guide:

### Setting up JWT

If you don't know how to do this refer to a guide like this one: https://medium.com/c-sharp-progarmming/asp-net-core-5-jwt-authentication-tutorial-with-example-api-aa59e80d02da

**Note: In my experience, this works best if the JWT configuration comes after the `AddUmbraco` chained statement**

An example can be seen here:

https://github.com/nikcio/Nikcio.UHeadless/blob/1792cb81e47058e4dcdf6ad6e9e1683ab412e7f4/test/v10/Startup.cs#L84-L90

Here I'm using the [Nikcio.ApiAuthentication](https://github.com/nikcio/Nikcio.ApiAuthentication) package that I made myself that sets up JWT. (**This package has not been updated in a while and I'm just using it for development purposes for the time being. So don't use this in a production application**)

### Setting up UHeadless

Once you've set up JWT, OAUTH, or some other authorization you can set up UHeadless.

First, modify the `AddUHeadless` statement in the `ConfigureServices` here you **need** to set the `UseSecurity` property to `true` for the authorization to work.

Example:
https://github.com/nikcio/Nikcio.UHeadless/blob/1792cb81e47058e4dcdf6ad6e9e1683ab412e7f4/test/v10/Startup.cs#L78

Next, you can set the `UseSecurity` setting on the `UseUHeadlessGraphQLEndpoint` if you'd like UHeadless to add the following statements:
```csharp
app.UseAuthentication();
app.UseAuthorization();
```

An example can be seen here: https://github.com/nikcio/Nikcio.UHeadless/blob/1792cb81e47058e4dcdf6ad6e9e1683ab412e7f4/test/v10/Startup.cs#L109

**Note: If you'd like to have the two statements separately then don't set `UseSecurity` to `true` in the `UseUHeadlessGraphQLEndpoint` statement. But be sure to place the statements BEFORE `UseUHeadlessGraphQLEndpoint` otherwise it will not work**

**If you look at the source code this setting only adds these two statements:** https://github.com/nikcio/Nikcio.UHeadless/blob/1792cb81e47058e4dcdf6ad6e9e1683ab412e7f4/src/Nikcio.UHeadless/Extensions/UHeadlessExtensions.cs#L90-L94

### Setting up your queries

Now that you have registered UHeadless to accept Authorization you can set your queries to require authorization.

To do this you need to make custom query models for the queries you'd like authorization on this can be done as easily as this:

https://github.com/nikcio/Nikcio.UHeadless/blob/1792cb81e47058e4dcdf6ad6e9e1683ab412e7f4/test/v10/Models/CustomContentQuery.cs#L18-L49

The package uses the built-in authorization system that Asp Net Core provides and you can therefore use the same customization that you would on a typical REST endpoint. This is done by adding the `[Authorize]` attribute.

**Note: This is not the standard Asp Net Core attribute but the one that comes from the `using HotChocolate.AspNetCore.Authorization;` namespace**

This is all done with the power that the Hot Chocolate framework brings. You can read more about how authorization works here: https://chillicream.com/docs/hotchocolate/security/authorization

And because it works from the default authorization flow you can also customize it with policies see: https://chillicream.com/docs/hotchocolate/security/authorization#policies

### Registering the queries

Once you have created the new authorized models you need to register that UHeadless should use them. To do this you add them to the UHeadless configuration:

https://github.com/nikcio/Nikcio.UHeadless/blob/1792cb81e47058e4dcdf6ad6e9e1683ab412e7f4/test/v10/Startup.cs#L67-L79

Place your models in the `GraphQLExtensions` section as seen above.

**Important note: When registering custom query models you override the defaults. This means that ONLY the queries registered are available at the GraphQL endpoint. Therefore, to use the default queries if you have not made your custom query for it adds the basic version. See the example below**

Example:

```csharp
builder.AddTypeExtension<BasicMediaQuery>();
```

### Extra: Authorization on the models

If you'd like more fine-grained customization you can also add the `[Authorize]` attribute inside your models. See how here: https://chillicream.com/docs/hotchocolate/security/authorization#usage

To figure out how to extend a model see the documentation.
For example:

* [Extend the existing content model](https://github.com/nikcio/Nikcio.UHeadless/blob/v3/contrib/docs/v3/content/extendExisting.md)
* [Extend an existing property value](https://github.com/nikcio/Nikcio.UHeadless/blob/v3/contrib/docs/v3/propertyValues/extendExistingSimple.md)
* [Create a new property value](https://github.com/nikcio/Nikcio.UHeadless/blob/v3/contrib/docs/v3/propertyValues/newValue.md)

**Comment by biapar** [comment]
Thank you very much for this explanation. I'll try today -:) and return to you with info.

**Comment by biapar** [comment]
I configured Umbraco with a custom code that generate JWT token with ASP.NET Core. Is there a simple example how to protect GraphQL endpoints into the controller? Is't enought to use the .NET core Authorize?

**Comment by nikcio** [comment]
https://github.com/nikcio/Nikcio.UHeadless/blob/v3/contrib/test/v10/Models/CustomContentQuery.cs
